name: bracket
dependencies:
  polymer:
      git:
          url: https://github.com/dart-lang/polymer-dart.git
          ref: 1.0.0-rc.10
  polymer_elements: 
  web_components: ^0.12.0
  reflectable: ^0.5.0
transformers:
- web_components:
    entry_points:
      - web/index.html
- reflectable:
    entry_points:
      - web/index.dart
