application: braket-o-matic
version: 1
module: default
runtime: go
api_version: go1

handlers:
- url: /backend/admin/.*
  script: _go_app
  secure: always
  login: admin

- url: /backend/.*
  script: _go_app
  secure: always
  login: required
