application: braketomatic
version: 1
module: frontend
runtime: go
api_version: go1

handlers:

- url: /packages
  static_dir: packages
  login: required
  secure: always

- url: /
  static_dir: static
  login: required
  secure: always
