application: braket-o-matic
version: 1
module: frontend
runtime: go
api_version: go1

handlers:

# Dart packages (but don't upload the dart code)
- url: /packages/(.*\.(js|dart|html))
  static_files: packages/\1
  upload: packages/(.*\.(js|html))
  login: required
  secure: always

# CSS, HTML, Dart, and JS files (don't upload Dart)
- url: /(.*\.(css|js|html|dart))
  static_files: static/\1
  upload: static/(.*\.(css|js|html))
  login: required
  secure: always

# Images
- url: /images/(.*\.(png|jpg|svg))
  static_files: static/images/\1
  upload: static/images/(.*\.(png|jpg|svg))
  login: required
  secure: always

# Site root
- url: /
  static_files: static/index.html
  upload: static/index.html
  login: required
  secure: always

# Admin tools
- url: /admin
  static_files: static/admin.html
  upload: static/admin.html
  login: admin
  secure: always
